language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_cache:
  - cargo clean -p serde-xml-rs
  - rm -rf target/
env:
  global:
    - RUST_BACKTRACE=1
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
