language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo clean -p serde-xml-rs
  - rm -f target/debug/deps/libserde_xml_rs*.rlib
  - cargo build --verbose
  - cargo test --verbose
cache: cargo
env:
  global:
    - RUST_BACKTRACE=1
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
